# ---------------------------------------------------------------------------
# Формат запису:
#   name       — назва (має бути унікальною)
#   calories   — ккал на 100 г
#   protein    — білки г на 100 г
#   fat        — жири г на 100 г
#   carbs      — вуглеводи г на 100 г
#   category   — категорія (для фільтрації)
#   aliases    — синоніми через кому (покращують пошук)
# ---------------------------------------------------------------------------
BUILTIN_PRODUCTS: list[dict] = [

    # ═══════════════════════════════════════════════════════════════════════
    # М'ЯСО ТА ПТИЦЯ
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "Куряча грудка варена", "calories": 165, "protein": 31.0, "fat": 3.6, "carbs": 0.0,
     "category": "meat", "aliases": "курятина, куряче філе, куряча грудь, chicken breast"},
    {"name": "Куряча грудка смажена", "calories": 197, "protein": 30.0, "fat": 8.0, "carbs": 0.0,
     "category": "meat", "aliases": "курка смажена, смажена курятина"},
    {"name": "Куряча грудка гриль", "calories": 165, "protein": 31.0, "fat": 3.8, "carbs": 0.0,
     "category": "meat", "aliases": "гриль курка, курка на грилі"},
    {"name": "Куряче стегно без шкіри варене", "calories": 182, "protein": 26.0, "fat": 8.7, "carbs": 0.0,
     "category": "meat", "aliases": "стегно курки, куряче стегно"},
    {"name": "Куряче стегно зі шкірою", "calories": 247, "protein": 23.0, "fat": 16.0, "carbs": 0.0,
     "category": "meat", "aliases": "стегно курки зі шкірою"},
    {"name": "Куряче крильце", "calories": 290, "protein": 27.0, "fat": 19.0, "carbs": 0.0,
     "category": "meat", "aliases": "крила курячі, крильця"},
    {"name": "Яловичина тушкована", "calories": 218, "protein": 25.0, "fat": 12.0, "carbs": 0.0,
     "category": "meat", "aliases": "яловичина, beef, говядина тушена"},
    {"name": "Яловичина відварна", "calories": 175, "protein": 26.0, "fat": 7.0, "carbs": 0.0,
     "category": "meat", "aliases": "яловичина варена, відварна говядина"},
    {"name": "Яловичина стейк", "calories": 271, "protein": 26.0, "fat": 18.0, "carbs": 0.0,
     "category": "meat", "aliases": "стейк, біфштекс, ribeye, стриплойн"},
    {"name": "Яловичий фарш", "calories": 254, "protein": 17.0, "fat": 20.0, "carbs": 0.0,
     "category": "meat", "aliases": "фарш яловичий, мелена яловичина"},
    {"name": "Свинина нежирна", "calories": 242, "protein": 27.0, "fat": 14.0, "carbs": 0.0,
     "category": "meat", "aliases": "свинина, pork, нежирна свинина"},
    {"name": "Свинина карбонад", "calories": 142, "protein": 19.0, "fat": 7.0, "carbs": 0.0,
     "category": "meat", "aliases": "карбонат, корейка свиняча"},
    {"name": "Свинячий фарш", "calories": 263, "protein": 17.0, "fat": 22.0, "carbs": 0.0,
     "category": "meat", "aliases": "фарш свинячий"},
    {"name": "Індичка філе варена", "calories": 157, "protein": 29.0, "fat": 3.8, "carbs": 0.0,
     "category": "meat", "aliases": "індик, turkey, індичка"},
    {"name": "Качка без шкіри", "calories": 201, "protein": 23.0, "fat": 11.0, "carbs": 0.0,
     "category": "meat", "aliases": "качатина, duck"},
    {"name": "Кролик тушкований", "calories": 162, "protein": 21.0, "fat": 8.0, "carbs": 0.0,
     "category": "meat", "aliases": "кроляча, м'ясо кролика"},
    {"name": "Печінка куряча", "calories": 140, "protein": 20.0, "fat": 5.5, "carbs": 1.0,
     "category": "meat", "aliases": "куряча печінка, субпродукти курки"},
    {"name": "Печінка яловича", "calories": 125, "protein": 20.0, "fat": 3.1, "carbs": 4.0,
     "category": "meat", "aliases": "яловича печінка, liver"},
    {"name": "Ковбаса докторська", "calories": 257, "protein": 13.0, "fat": 22.0, "carbs": 2.3,
     "category": "meat", "aliases": "варена ковбаса, сосиски"},
    {"name": "Сосиски курячі", "calories": 198, "protein": 14.0, "fat": 16.0, "carbs": 1.0,
     "category": "meat", "aliases": "курячі сосиски, сардельки"},
    {"name": "Бекон", "calories": 417, "protein": 12.0, "fat": 42.0, "carbs": 0.0,
     "category": "meat", "aliases": "bacon, грудинка копчена"},

    # ═══════════════════════════════════════════════════════════════════════
    # РИБА ТА МОРЕПРОДУКТИ
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "Лосось запечений", "calories": 208, "protein": 25.0, "fat": 12.0, "carbs": 0.0,
     "category": "fish", "aliases": "лосось, сьомга, salmon, форель"},
    {"name": "Лосось свіжий сирий", "calories": 208, "protein": 20.0, "fat": 13.0, "carbs": 0.0,
     "category": "fish", "aliases": "сирий лосось, сьомга сира"},
    {"name": "Тунець у власному соку", "calories": 116, "protein": 26.0, "fat": 1.0, "carbs": 0.0,
     "category": "fish", "aliases": "тунець консерви, tuna"},
    {"name": "Тунець свіжий", "calories": 144, "protein": 23.0, "fat": 5.0, "carbs": 0.0,
     "category": "fish", "aliases": "стейк тунця, тунець гриль"},
    {"name": "Хек варений", "calories": 95, "protein": 18.0, "fat": 2.0, "carbs": 0.0,
     "category": "fish", "aliases": "хек, мерлуза, минтай"},
    {"name": "Минтай запечений", "calories": 90, "protein": 18.5, "fat": 1.0, "carbs": 0.0,
     "category": "fish", "aliases": "минтай, pollock"},
    {"name": "Тріска варена", "calories": 98, "protein": 23.0, "fat": 0.7, "carbs": 0.0,
     "category": "fish", "aliases": "тріска, cod"},
    {"name": "Скумбрія запечена", "calories": 262, "protein": 20.0, "fat": 20.0, "carbs": 0.0,
     "category": "fish", "aliases": "скумбрія, mackerel"},
    {"name": "Оселедець", "calories": 217, "protein": 18.0, "fat": 16.0, "carbs": 0.0,
     "category": "fish", "aliases": "оселедець солоний, herring"},
    {"name": "Сардини консерви", "calories": 208, "protein": 24.0, "fat": 12.0, "carbs": 0.0,
     "category": "fish", "aliases": "сардини, sardines"},
    {"name": "Креветки відварені", "calories": 99, "protein": 24.0, "fat": 0.3, "carbs": 0.0,
     "category": "fish", "aliases": "креветка, shrimp, prawns"},
    {"name": "Кальмар варений", "calories": 110, "protein": 18.0, "fat": 4.0, "carbs": 0.0,
     "category": "fish", "aliases": "кальмари, squid"},
    {"name": "Мідії варені", "calories": 86, "protein": 12.0, "fat": 2.0, "carbs": 4.0,
     "category": "fish", "aliases": "мідія, mussels"},

    # ═══════════════════════════════════════════════════════════════════════
    # ЯЙЦЯ
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "Яйце куряче варене", "calories": 155, "protein": 13.0, "fat": 11.0, "carbs": 1.1,
     "category": "eggs", "aliases": "яйце, egg, яйця, варене яйце"},
    {"name": "Яйце смажене", "calories": 196, "protein": 14.0, "fat": 15.0, "carbs": 0.6,
     "category": "eggs", "aliases": "яєчня, смажені яйця, глазунья"},
    {"name": "Яйце перепелине", "calories": 158, "protein": 13.0, "fat": 11.0, "carbs": 0.6,
     "category": "eggs", "aliases": "перепелині яйця"},
    {"name": "Омлет на молоці", "calories": 154, "protein": 10.0, "fat": 12.0, "carbs": 1.5,
     "category": "eggs", "aliases": "омлет, omelette"},
    {"name": "Яєчний білок", "calories": 52, "protein": 11.0, "fat": 0.2, "carbs": 0.7,
     "category": "eggs", "aliases": "білок яйця, egg white"},

    # ═══════════════════════════════════════════════════════════════════════
    # ЗЛАКИ, КРУПИ ТА МАКАРОНИ
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "Гречка варена", "calories": 110, "protein": 4.0, "fat": 1.0, "carbs": 21.0,
     "category": "grains", "aliases": "гречана каша, buckwheat, гречка"},
    {"name": "Гречка суха", "calories": 343, "protein": 13.0, "fat": 3.4, "carbs": 62.0,
     "category": "grains", "aliases": "гречана крупа суха"},
    {"name": "Рис білий варений", "calories": 130, "protein": 2.7, "fat": 0.3, "carbs": 28.0,
     "category": "grains", "aliases": "рис, white rice, рисова каша"},
    {"name": "Рис бурий варений", "calories": 112, "protein": 2.3, "fat": 0.9, "carbs": 23.0,
     "category": "grains", "aliases": "коричневий рис, brown rice"},
    {"name": "Рис басматі варений", "calories": 121, "protein": 3.5, "fat": 0.4, "carbs": 25.0,
     "category": "grains", "aliases": "басматі, basmati"},
    {"name": "Вівсянка на воді", "calories": 68, "protein": 2.5, "fat": 1.5, "carbs": 12.0,
     "category": "grains", "aliases": "вівсяна каша, oatmeal, геркулес, вівсянка"},
    {"name": "Вівсянка на молоці", "calories": 95, "protein": 3.8, "fat": 3.5, "carbs": 13.0,
     "category": "grains", "aliases": "вівсяна каша з молоком"},
    {"name": "Перлова каша варена", "calories": 102, "protein": 3.0, "fat": 0.4, "carbs": 22.0,
     "category": "grains", "aliases": "перловка, перлова крупа"},
    {"name": "Пшоняна каша на воді", "calories": 90, "protein": 3.0, "fat": 1.0, "carbs": 17.0,
     "category": "grains", "aliases": "пшоно, просо, пшоняна"},
    {"name": "Кукурудзяна каша", "calories": 86, "protein": 2.5, "fat": 1.0, "carbs": 18.0,
     "category": "grains", "aliases": "мамалига, кукурудзяна крупа, polenta"},
    {"name": "Макарони варені", "calories": 158, "protein": 5.5, "fat": 0.9, "carbs": 31.0,
     "category": "grains", "aliases": "паста, pasta, спагетті, пенне, фарфалі"},
    {"name": "Спагетті варені", "calories": 157, "protein": 5.8, "fat": 0.9, "carbs": 30.0,
     "category": "grains", "aliases": "spaghetti, спагеті"},
    {"name": "Кіноа варена", "calories": 120, "protein": 4.4, "fat": 1.9, "carbs": 21.0,
     "category": "grains", "aliases": "quinoa, кіноа"},
    {"name": "Булгур варений", "calories": 83, "protein": 3.1, "fat": 0.2, "carbs": 18.0,
     "category": "grains", "aliases": "bulgur, булгур"},
    {"name": "Кускус варений", "calories": 112, "protein": 3.8, "fat": 0.2, "carbs": 23.0,
     "category": "grains", "aliases": "couscous, кускус"},
    {"name": "Вівсяні пластівці сухі", "calories": 389, "protein": 17.0, "fat": 7.0, "carbs": 66.0,
     "category": "grains", "aliases": "геркулес сухий, rolled oats"},
    {"name": "Висівки вівсяні", "calories": 246, "protein": 17.0, "fat": 7.0, "carbs": 66.0,
     "category": "grains", "aliases": "oat bran, вівсяні висівки"},

    # ═══════════════════════════════════════════════════════════════════════
    # ХЛІБ, ВИПІЧКА, БОРОШНЯНЕ
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "Хліб чорний", "calories": 214, "protein": 6.8, "fat": 1.2, "carbs": 41.0,
     "category": "bread", "aliases": "житній хліб, чорний хліб, ржаний хліб"},
    {"name": "Хліб білий", "calories": 242, "protein": 7.7, "fat": 2.4, "carbs": 48.0,
     "category": "bread", "aliases": "пшеничний хліб, білий хліб"},
    {"name": "Хліб цільнозерновий", "calories": 198, "protein": 8.0, "fat": 2.0, "carbs": 37.0,
     "category": "bread", "aliases": "цільнозерновий, whole grain bread, зерновий хліб"},
    {"name": "Батон", "calories": 262, "protein": 7.9, "fat": 3.2, "carbs": 51.0,
     "category": "bread", "aliases": "батон білий, французький батон"},
    {"name": "Лаваш тонкий", "calories": 277, "protein": 9.0, "fat": 1.0, "carbs": 57.0,
     "category": "bread", "aliases": "лаваш, pita, піта"},
    {"name": "Хлібці рисові", "calories": 381, "protein": 7.5, "fat": 3.0, "carbs": 82.0,
     "category": "bread", "aliases": "рисові хлібці, хлібці"},
    {"name": "Млинці", "calories": 233, "protein": 6.1, "fat": 12.0, "carbs": 26.0,
     "category": "bread", "aliases": "млинці, pancakes, налисники"},
    {"name": "Вареники з картоплею", "calories": 170, "protein": 5.0, "fat": 2.0, "carbs": 34.0,
     "category": "bread", "aliases": "вареники, dumplings"},

    # ═══════════════════════════════════════════════════════════════════════
    # МОЛОЧНІ ПРОДУКТИ
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "Молоко 1%", "calories": 41, "protein": 3.4, "fat": 1.0, "carbs": 5.0,
     "category": "dairy", "aliases": "знежирене молоко, milk"},
    {"name": "Молоко 2.5%", "calories": 52, "protein": 2.9, "fat": 2.5, "carbs": 4.7,
     "category": "dairy", "aliases": "молоко, milk 2.5"},
    {"name": "Молоко 3.2%", "calories": 60, "protein": 2.9, "fat": 3.2, "carbs": 4.7,
     "category": "dairy", "aliases": "молоко жирне, цільне молоко"},
    {"name": "Кефір 1%", "calories": 40, "protein": 3.0, "fat": 1.0, "carbs": 4.0,
     "category": "dairy", "aliases": "кефір, kefir"},
    {"name": "Кефір 2.5%", "calories": 53, "protein": 2.9, "fat": 2.5, "carbs": 3.9,
     "category": "dairy", "aliases": "кефір жирний"},
    {"name": "Ряжанка 2.5%", "calories": 54, "protein": 2.9, "fat": 2.5, "carbs": 4.2,
     "category": "dairy", "aliases": "ряжанка"},
    {"name": "Грецький йогурт 0%", "calories": 57, "protein": 10.0, "fat": 0.4, "carbs": 3.6,
     "category": "dairy", "aliases": "грецький йогурт, greek yogurt, знежирений йогурт"},
    {"name": "Грецький йогурт 2%", "calories": 73, "protein": 10.0, "fat": 2.0, "carbs": 4.0,
     "category": "dairy", "aliases": "йогурт грецький"},
    {"name": "Йогурт натуральний", "calories": 68, "protein": 3.5, "fat": 1.5, "carbs": 9.0,
     "category": "dairy", "aliases": "йогурт без добавок, натуральний йогурт"},
    {"name": "Сметана 10%", "calories": 115, "protein": 3.0, "fat": 10.0, "carbs": 2.9,
     "category": "dairy", "aliases": "сметана, sour cream"},
    {"name": "Сметана 20%", "calories": 206, "protein": 2.8, "fat": 20.0, "carbs": 3.2,
     "category": "dairy", "aliases": "жирна сметана"},
    {"name": "Сир кисломолочний 0%", "calories": 71, "protein": 18.0, "fat": 0.6, "carbs": 1.8,
     "category": "dairy", "aliases": "знежирений творог, сир 0%, cottage cheese"},
    {"name": "Сир кисломолочний 5%", "calories": 121, "protein": 17.0, "fat": 5.0, "carbs": 2.7,
     "category": "dairy", "aliases": "творог, сир 5%, cottage cheese 5%"},
    {"name": "Сир кисломолочний 9%", "calories": 159, "protein": 16.0, "fat": 9.0, "carbs": 2.0,
     "category": "dairy", "aliases": "творог 9%, жирний сир"},
    {"name": "Сир твердий гауда", "calories": 356, "protein": 25.0, "fat": 27.0, "carbs": 2.2,
     "category": "dairy", "aliases": "гауда, gouda, твердий сир"},
    {"name": "Сир пармезан", "calories": 431, "protein": 38.0, "fat": 29.0, "carbs": 4.1,
     "category": "dairy", "aliases": "пармезан, parmesan"},
    {"name": "Сир моцарела", "calories": 280, "protein": 18.0, "fat": 22.0, "carbs": 2.2,
     "category": "dairy", "aliases": "моцарела, mozzarella"},
    {"name": "Сир фета", "calories": 264, "protein": 14.0, "fat": 21.0, "carbs": 4.1,
     "category": "dairy", "aliases": "фета, feta"},
    {"name": "Масло вершкове", "calories": 717, "protein": 0.9, "fat": 81.0, "carbs": 0.1,
     "category": "dairy", "aliases": "вершкове масло, butter"},
    {"name": "Вершки 10%", "calories": 119, "protein": 2.7, "fat": 10.0, "carbs": 4.0,
     "category": "dairy", "aliases": "вершки, cream 10%"},
    {"name": "Вершки 33%", "calories": 322, "protein": 2.2, "fat": 33.0, "carbs": 3.5,
     "category": "dairy", "aliases": "жирні вершки, heavy cream"},

    # ═══════════════════════════════════════════════════════════════════════
    # БОБОВІ
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "Сочевиця варена", "calories": 116, "protein": 9.0, "fat": 0.4, "carbs": 20.0,
     "category": "legumes", "aliases": "сочевиця, lentils"},
    {"name": "Нут варений", "calories": 164, "protein": 8.9, "fat": 2.6, "carbs": 27.0,
     "category": "legumes", "aliases": "нут, chickpeas, горох нут"},
    {"name": "Квасоля варена", "calories": 127, "protein": 8.7, "fat": 0.5, "carbs": 23.0,
     "category": "legumes", "aliases": "квасоля, beans, фасоль"},
    {"name": "Горох варений", "calories": 116, "protein": 8.0, "fat": 0.4, "carbs": 20.0,
     "category": "legumes", "aliases": "горох, peas"},
    {"name": "Едамаме", "calories": 122, "protein": 11.0, "fat": 5.0, "carbs": 9.0,
     "category": "legumes", "aliases": "едамаме, edamame, соєві боби"},
    {"name": "Тофу", "calories": 76, "protein": 8.0, "fat": 4.0, "carbs": 2.0,
     "category": "legumes", "aliases": "tofu, соєвий сир"},
    {"name": "Хумус", "calories": 177, "protein": 8.0, "fat": 10.0, "carbs": 14.0,
     "category": "legumes", "aliases": "хумус, hummus"},

    # ═══════════════════════════════════════════════════════════════════════
    # ОВОЧІ
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "Картопля варена", "calories": 86, "protein": 2.0, "fat": 0.1, "carbs": 19.0,
     "category": "vegetables", "aliases": "картопля, potatoes, бульба"},
    {"name": "Картопля запечена", "calories": 93, "protein": 2.5, "fat": 0.1, "carbs": 21.0,
     "category": "vegetables", "aliases": "запечена картопля"},
    {"name": "Картопляне пюре", "calories": 83, "protein": 2.0, "fat": 1.0, "carbs": 17.0,
     "category": "vegetables", "aliases": "пюре, mashed potatoes"},
    {"name": "Картопля фрі", "calories": 312, "protein": 3.4, "fat": 15.0, "carbs": 41.0,
     "category": "vegetables", "aliases": "french fries, смажена картопля фрі"},
    {"name": "Броколі варена", "calories": 35, "protein": 2.4, "fat": 0.4, "carbs": 5.0,
     "category": "vegetables", "aliases": "броколі, broccoli"},
    {"name": "Броколі сира", "calories": 34, "protein": 2.8, "fat": 0.4, "carbs": 6.6,
     "category": "vegetables", "aliases": "свіжа броколі"},
    {"name": "Морква варена", "calories": 35, "protein": 0.8, "fat": 0.2, "carbs": 8.0,
     "category": "vegetables", "aliases": "морква, carrots"},
    {"name": "Морква свіжа", "calories": 41, "protein": 0.9, "fat": 0.2, "carbs": 10.0,
     "category": "vegetables", "aliases": "свіжа морква, сира морква"},
    {"name": "Буряк варений", "calories": 44, "protein": 1.7, "fat": 0.1, "carbs": 9.6,
     "category": "vegetables", "aliases": "буряк, beet, бурячок"},
    {"name": "Капуста тушкована", "calories": 75, "protein": 1.8, "fat": 5.0, "carbs": 6.0,
     "category": "vegetables", "aliases": "тушкована капуста, капуста"},
    {"name": "Капуста свіжа", "calories": 25, "protein": 1.3, "fat": 0.1, "carbs": 5.8,
     "category": "vegetables", "aliases": "свіжа капуста, білокачанна капуста, cabbage"},
    {"name": "Цвітна капуста варена", "calories": 25, "protein": 2.0, "fat": 0.3, "carbs": 4.1,
     "category": "vegetables", "aliases": "цвітна капуста, cauliflower"},
    {"name": "Огірок свіжий", "calories": 15, "protein": 0.7, "fat": 0.1, "carbs": 3.6,
     "category": "vegetables", "aliases": "огірок, cucumber"},
    {"name": "Помідор свіжий", "calories": 18, "protein": 0.9, "fat": 0.2, "carbs": 3.9,
     "category": "vegetables", "aliases": "помідор, tomato, томат"},
    {"name": "Болгарський перець", "calories": 27, "protein": 1.0, "fat": 0.3, "carbs": 6.0,
     "category": "vegetables", "aliases": "солодкий перець, bell pepper, паприка"},
    {"name": "Цукіні варений", "calories": 17, "protein": 1.2, "fat": 0.3, "carbs": 3.1,
     "category": "vegetables", "aliases": "цукіні, кабачок, zucchini"},
    {"name": "Гарбуз варений", "calories": 20, "protein": 0.9, "fat": 0.1, "carbs": 4.5,
     "category": "vegetables", "aliases": "гарбуз, pumpkin"},
    {"name": "Баклажан запечений", "calories": 35, "protein": 0.9, "fat": 0.2, "carbs": 8.7,
     "category": "vegetables", "aliases": "баклажан, eggplant"},
    {"name": "Шпинат свіжий", "calories": 23, "protein": 2.9, "fat": 0.4, "carbs": 3.6,
     "category": "vegetables", "aliases": "шпинат, spinach"},
    {"name": "Авокадо", "calories": 160, "protein": 2.0, "fat": 15.0, "carbs": 9.0,
     "category": "vegetables", "aliases": "авокадо, avocado"},
    {"name": "Кукурудза варена", "calories": 96, "protein": 3.3, "fat": 1.4, "carbs": 21.0,
     "category": "vegetables", "aliases": "кукурудза, corn"},
    {"name": "Зелений горошок", "calories": 81, "protein": 5.0, "fat": 0.4, "carbs": 14.0,
     "category": "vegetables", "aliases": "зелений горох, peas, горошок"},
    {"name": "Цибуля ріпчаста", "calories": 40, "protein": 1.1, "fat": 0.1, "carbs": 9.0,
     "category": "vegetables", "aliases": "цибуля, onion"},
    {"name": "Часник", "calories": 149, "protein": 6.4, "fat": 0.5, "carbs": 33.0,
     "category": "vegetables", "aliases": "часник, garlic"},
    {"name": "Гриби печериці", "calories": 27, "protein": 3.1, "fat": 0.3, "carbs": 3.3,
     "category": "vegetables", "aliases": "гриби, mushrooms, печериці, шампіньйони"},
    {"name": "Гриби лисички варені", "calories": 40, "protein": 2.0, "fat": 0.5, "carbs": 7.0,
     "category": "vegetables", "aliases": "лисички, chanterelles"},

    # ═══════════════════════════════════════════════════════════════════════
    # ФРУКТИ ТА ЯГОДИ
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "Яблуко", "calories": 52, "protein": 0.3, "fat": 0.2, "carbs": 14.0,
     "category": "fruits", "aliases": "яблуко, apple"},
    {"name": "Банан", "calories": 89, "protein": 1.1, "fat": 0.3, "carbs": 23.0,
     "category": "fruits", "aliases": "банан, banana"},
    {"name": "Апельсин", "calories": 47, "protein": 0.9, "fat": 0.1, "carbs": 12.0,
     "category": "fruits", "aliases": "апельсин, orange"},
    {"name": "Мандарин", "calories": 53, "protein": 0.8, "fat": 0.2, "carbs": 13.0,
     "category": "fruits", "aliases": "мандарин, tangerine, clementine"},
    {"name": "Грейпфрут", "calories": 42, "protein": 0.8, "fat": 0.1, "carbs": 11.0,
     "category": "fruits", "aliases": "грейпфрут, grapefruit"},
    {"name": "Груша", "calories": 57, "protein": 0.4, "fat": 0.1, "carbs": 15.0,
     "category": "fruits", "aliases": "груша, pear"},
    {"name": "Персик", "calories": 39, "protein": 0.9, "fat": 0.3, "carbs": 10.0,
     "category": "fruits", "aliases": "персик, peach"},
    {"name": "Абрикос", "calories": 48, "protein": 1.4, "fat": 0.4, "carbs": 11.0,
     "category": "fruits", "aliases": "абрикос, apricot"},
    {"name": "Виноград", "calories": 69, "protein": 0.7, "fat": 0.2, "carbs": 18.0,
     "category": "fruits", "aliases": "виноград, grapes"},
    {"name": "Кавун", "calories": 30, "protein": 0.6, "fat": 0.2, "carbs": 7.6,
     "category": "fruits", "aliases": "кавун, watermelon"},
    {"name": "Диня", "calories": 34, "protein": 0.8, "fat": 0.2, "carbs": 8.0,
     "category": "fruits", "aliases": "диня, melon"},
    {"name": "Ананас", "calories": 50, "protein": 0.5, "fat": 0.1, "carbs": 13.0,
     "category": "fruits", "aliases": "ананас, pineapple"},
    {"name": "Манго", "calories": 60, "protein": 0.8, "fat": 0.4, "carbs": 15.0,
     "category": "fruits", "aliases": "манго, mango"},
    {"name": "Полуниця", "calories": 32, "protein": 0.7, "fat": 0.3, "carbs": 7.7,
     "category": "fruits", "aliases": "полуниця, strawberry"},
    {"name": "Чорниця", "calories": 57, "protein": 0.7, "fat": 0.3, "carbs": 14.0,
     "category": "fruits", "aliases": "чорниця, blueberry"},
    {"name": "Малина", "calories": 52, "protein": 1.2, "fat": 0.6, "carbs": 12.0,
     "category": "fruits", "aliases": "малина, raspberry"},
    {"name": "Вишня", "calories": 50, "protein": 1.0, "fat": 0.3, "carbs": 12.0,
     "category": "fruits", "aliases": "вишня, cherry"},
    {"name": "Смородина чорна", "calories": 63, "protein": 1.4, "fat": 0.5, "carbs": 15.0,
     "category": "fruits", "aliases": "чорна смородина, blackcurrant"},
    {"name": "Фінік сухий", "calories": 282, "protein": 2.5, "fat": 0.4, "carbs": 75.0,
     "category": "fruits", "aliases": "фінік, dates"},

    # ═══════════════════════════════════════════════════════════════════════
    # ГОРІХИ ТА НАСІННЯ
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "Мигдаль", "calories": 579, "protein": 21.0, "fat": 50.0, "carbs": 22.0,
     "category": "nuts", "aliases": "мигдаль, almonds"},
    {"name": "Волоський горіх", "calories": 654, "protein": 15.0, "fat": 65.0, "carbs": 14.0,
     "category": "nuts", "aliases": "волоські горіхи, walnuts"},
    {"name": "Фундук", "calories": 628, "protein": 15.0, "fat": 61.0, "carbs": 17.0,
     "category": "nuts", "aliases": "фундук, hazelnuts, ліщина"},
    {"name": "Кешью", "calories": 553, "protein": 18.0, "fat": 44.0, "carbs": 30.0,
     "category": "nuts", "aliases": "кешью, cashews"},
    {"name": "Арахіс", "calories": 567, "protein": 26.0, "fat": 49.0, "carbs": 16.0,
     "category": "nuts", "aliases": "арахіс, peanuts, земляний горіх"},
    {"name": "Арахісова паста", "calories": 588, "protein": 25.0, "fat": 50.0, "carbs": 20.0,
     "category": "nuts", "aliases": "арахісове масло, peanut butter"},
    {"name": "Насіння чіа", "calories": 486, "protein": 17.0, "fat": 31.0, "carbs": 42.0,
     "category": "nuts", "aliases": "чіа, chia seeds"},
    {"name": "Насіння льону", "calories": 534, "protein": 18.0, "fat": 42.0, "carbs": 29.0,
     "category": "nuts", "aliases": "льон, flaxseed, лляне насіння"},
    {"name": "Насіння соняшнику", "calories": 584, "protein": 21.0, "fat": 51.0, "carbs": 20.0,
     "category": "nuts", "aliases": "соняшникове насіння, sunflower seeds"},
    {"name": "Гарбузове насіння", "calories": 559, "protein": 30.0, "fat": 49.0, "carbs": 11.0,
     "category": "nuts", "aliases": "гарбузові насіння, pumpkin seeds"},
    {"name": "Кокос сухий", "calories": 354, "protein": 3.3, "fat": 33.0, "carbs": 15.0,
     "category": "nuts", "aliases": "кокос, coconut"},

    # ═══════════════════════════════════════════════════════════════════════
    # ОЛІЇ ТА ЖИРИ
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "Олія соняшникова", "calories": 884, "protein": 0.0, "fat": 100.0, "carbs": 0.0,
     "category": "oils", "aliases": "соняшникова олія, sunflower oil"},
    {"name": "Олія оливкова", "calories": 884, "protein": 0.0, "fat": 100.0, "carbs": 0.0,
     "category": "oils", "aliases": "оливкова олія, olive oil, extra virgin"},
    {"name": "Олія кокосова", "calories": 862, "protein": 0.0, "fat": 100.0, "carbs": 0.0,
     "category": "oils", "aliases": "кокосова олія, coconut oil"},
    {"name": "Майонез класичний", "calories": 680, "protein": 1.0, "fat": 75.0, "carbs": 2.6,
     "category": "oils", "aliases": "майонез, mayonnaise"},
    {"name": "Майонез легкий", "calories": 260, "protein": 1.0, "fat": 26.0, "carbs": 5.0,
     "category": "oils", "aliases": "легкий майонез, low-fat mayo"},

    # ═══════════════════════════════════════════════════════════════════════
    # ГОТОВІ СТРАВИ
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "Борщ", "calories": 48, "protein": 2.5, "fat": 1.8, "carbs": 6.0,
     "category": "dishes", "aliases": "борщ, borscht, борщик"},
    {"name": "Суп курячий", "calories": 36, "protein": 3.0, "fat": 1.5, "carbs": 2.5,
     "category": "dishes", "aliases": "куриний суп, курячий бульйон, chicken soup"},
    {"name": "Суп гороховий", "calories": 66, "protein": 4.0, "fat": 1.5, "carbs": 9.5,
     "category": "dishes", "aliases": "гороховий суп, pea soup"},
    {"name": "Суп харчо", "calories": 68, "protein": 4.5, "fat": 2.5, "carbs": 8.0,
     "category": "dishes", "aliases": "харчо, lamb soup"},
    {"name": "Салат Цезар з куркою", "calories": 190, "protein": 12.0, "fat": 14.0, "carbs": 6.0,
     "category": "dishes", "aliases": "цезар, caesar salad"},
    {"name": "Салат Олів'є", "calories": 198, "protein": 6.5, "fat": 16.0, "carbs": 8.0,
     "category": "dishes", "aliases": "олів'є, салат з майонезом, оливье"},
    {"name": "Вінегрет", "calories": 70, "protein": 1.5, "fat": 3.5, "carbs": 8.0,
     "category": "dishes", "aliases": "вінегрет, vinegret"},
    {"name": "Піца маргарита", "calories": 266, "protein": 11.0, "fat": 10.0, "carbs": 33.0,
     "category": "dishes", "aliases": "піца, pizza margherita, марґарита"},
    {"name": "Піца пепероні", "calories": 298, "protein": 13.0, "fat": 13.0, "carbs": 33.0,
     "category": "dishes", "aliases": "пепероні, pepperoni pizza"},
    {"name": "Шаурма куряча", "calories": 230, "protein": 14.0, "fat": 10.0, "carbs": 22.0,
     "category": "dishes", "aliases": "шаурма, shawarma, шаверма"},
    {"name": "Котлета куряча парова", "calories": 148, "protein": 18.0, "fat": 7.0, "carbs": 4.0,
     "category": "dishes", "aliases": "парова котлета, куряча котлета"},
    {"name": "Котлета м'ясна смажена", "calories": 255, "protein": 15.0, "fat": 20.0, "carbs": 6.0,
     "category": "dishes", "aliases": "смажена котлета, відбивна, schnitzel"},
    {"name": "Сирники", "calories": 210, "protein": 14.0, "fat": 8.0, "carbs": 20.0,
     "category": "dishes", "aliases": "сирники, cottage cheese pancakes, запіканка"},
    {"name": "Плов", "calories": 217, "protein": 8.0, "fat": 10.0, "carbs": 25.0,
     "category": "dishes", "aliases": "плов, pilaf, рис з м'ясом"},
    {"name": "Голубці", "calories": 148, "protein": 8.0, "fat": 8.0, "carbs": 12.0,
     "category": "dishes", "aliases": "голубці, stuffed cabbage rolls"},
    {"name": "Вареники з м'ясом", "calories": 253, "protein": 13.0, "fat": 11.0, "carbs": 26.0,
     "category": "dishes", "aliases": "вареники м'ясні, пельмені"},
    {"name": "Пельмені", "calories": 275, "protein": 11.0, "fat": 13.0, "carbs": 28.0,
     "category": "dishes", "aliases": "пельмені, dumplings"},
    {"name": "Гречка з куркою", "calories": 136, "protein": 14.0, "fat": 2.8, "carbs": 15.0,
     "category": "dishes", "aliases": "гречка з м'ясом, гречка з курятиною"},
    {"name": "Рис з куркою", "calories": 145, "protein": 12.0, "fat": 3.0, "carbs": 19.0,
     "category": "dishes", "aliases": "рис з курятиною"},
    {"name": "Паста болоньєзе", "calories": 188, "protein": 11.0, "fat": 7.0, "carbs": 22.0,
     "category": "dishes", "aliases": "болоньєзе, bolognese, паста з м'ясним соусом"},
    {"name": "Паста карбонара", "calories": 380, "protein": 17.0, "fat": 22.0, "carbs": 30.0,
     "category": "dishes", "aliases": "карбонара, carbonara"},
    {"name": "Бургер", "calories": 295, "protein": 15.0, "fat": 14.0, "carbs": 27.0,
     "category": "dishes", "aliases": "бургер, hamburger, чізбургер"},
    {"name": "Суші (ролл)", "calories": 150, "protein": 5.0, "fat": 4.0, "carbs": 24.0,
     "category": "dishes", "aliases": "суші, ролли, sushi, rolls"},
    {"name": "Яловичина з овочами тушкована", "calories": 135, "protein": 13.0, "fat": 6.0, "carbs": 8.0,
     "category": "dishes", "aliases": "м'ясо з овочами, beef stew"},

    # ═══════════════════════════════════════════════════════════════════════
    # СПОРТИВНЕ ХАРЧУВАННЯ
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "Протеїновий коктейль", "calories": 130, "protein": 25.0, "fat": 2.0, "carbs": 5.0,
     "category": "sport", "aliases": "протеїн, protein shake, сироватковий протеїн"},
    {"name": "Протеїновий батончик", "calories": 350, "protein": 30.0, "fat": 8.0, "carbs": 35.0,
     "category": "sport", "aliases": "протеїновий батончик, protein bar"},
    {"name": "BCAA", "calories": 20, "protein": 5.0, "fat": 0.0, "carbs": 0.0,
     "category": "sport", "aliases": "bcaa, амінокислоти"},
    {"name": "Гейнер", "calories": 400, "protein": 30.0, "fat": 5.0, "carbs": 60.0,
     "category": "sport", "aliases": "gainer, маса, масонабір"},

    # ═══════════════════════════════════════════════════════════════════════
    # СОЛОДОЩІ ТА СНЕКИ
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "Шоколад темний 70%", "calories": 604, "protein": 7.8, "fat": 43.0, "carbs": 46.0,
     "category": "sweets", "aliases": "темний шоколад, dark chocolate, гіркий шоколад"},
    {"name": "Шоколад молочний", "calories": 535, "protein": 7.0, "fat": 30.0, "carbs": 60.0,
     "category": "sweets", "aliases": "молочний шоколад, milk chocolate"},
    {"name": "Мед", "calories": 304, "protein": 0.3, "fat": 0.0, "carbs": 82.0,
     "category": "sweets", "aliases": "мед, honey"},
    {"name": "Джем", "calories": 265, "protein": 0.4, "fat": 0.1, "carbs": 68.0,
     "category": "sweets", "aliases": "джем, jam, варення"},
    {"name": "Мармелад", "calories": 321, "protein": 0.1, "fat": 0.0, "carbs": 80.0,
     "category": "sweets", "aliases": "мармелад, jelly"},
    {"name": "Чіпси", "calories": 536, "protein": 7.0, "fat": 35.0, "carbs": 53.0,
     "category": "sweets", "aliases": "чіпси, chips, crisps"},
    {"name": "Попкорн", "calories": 387, "protein": 12.0, "fat": 4.5, "carbs": 78.0,
     "category": "sweets", "aliases": "попкорн, popcorn"},
    {"name": "Морозиво ванільне", "calories": 207, "protein": 3.5, "fat": 11.0, "carbs": 24.0,
     "category": "sweets", "aliases": "морозиво, ice cream"},

    # ═══════════════════════════════════════════════════════════════════════
    # НАПОЇ
    # ═══════════════════════════════════════════════════════════════════════
    {"name": "Апельсиновий сік свіжовижатий", "calories": 45, "protein": 0.7, "fat": 0.2, "carbs": 10.0,
     "category": "drinks", "aliases": "апельсиновий сік, orange juice"},
    {"name": "Яблучний сік", "calories": 46, "protein": 0.1, "fat": 0.1, "carbs": 11.0,
     "category": "drinks", "aliases": "яблучний сік, apple juice"},
    {"name": "Кава з молоком", "calories": 39, "protein": 1.5, "fat": 1.8, "carbs": 4.0,
     "category": "drinks", "aliases": "кава з молоком, latte, капучино"},
    {"name": "Смузі банановий", "calories": 90, "protein": 1.2, "fat": 0.5, "carbs": 21.0,
     "category": "drinks", "aliases": "банановий смузі, banana smoothie"},
]
